
######################################################################
# Automatically generated by qmake (2.01a) Fri May 29 03:37:18 2015
######################################################################



QT += core network script
TEMPLATE = app
TARGET = intrecx
DEPENDPATH += .
INCLUDEPATH += .

 
# Input
HEADERS += rec.h recx.h
SOURCES += main.cpp recx.cpp
