######################################################################
# Automatically generated by qmake (2.01a) Fri May 8 01:13:15 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
# Input
HEADERS += recx.h
SOURCES += main.cpp recx.cpp

QT += core network
QT -= gui widgets
